from flask import Flask, request, jsonify, send_from_directory, render_template, redirect, url_for, session
from flask_cors import CORS
from werkzeug.security import generate_password_hash, check_password_hash
from pymongo import MongoClient
from bson.objectid import ObjectId
from datetime import datetime
import os
import logging
app = Flask(__name__, static_folder="public")
app.secret_key = os.urandom(24)  # Secure random secret key
CORS(app)

# MongoDB connection

client = MongoClient("mongodb+srv://nanthithaponnusamy:123@cluster0.dqri55s.mongodb.net/cake_shop?retryWrites=true&w=majority")

try:
    print(client.list_database_names())
    print("✅ Connected successfully")
except Exception as e:
    print("❌ Error:", e)
db = client["cake_shop"]
users = db["users"]
orders = db["orders"]
contacts = db["contacts"]

# ========== AUTH ROUTES ==========

@app.route("/signup", methods=["POST"])
def signup():
    data = request.json
    name = data.get("name")
    email = data.get("email")
    password = data.get("password")
    
    if users.find_one({"email": email}):
        return jsonify({"message": "User already exists"}), 400

    users.insert_one({"name": name, "email": email, "password": password})
    return jsonify({"message": "User registered successfully"})

@app.route("/login", methods=["POST"])
def login():
    data = request.json
    email = data.get("email")
    password = data.get("password")

    user = users.find_one({"email": email, "password": password})
    if user:
        session['user_email'] = email
        return jsonify({"message": "Login successful"})
    return jsonify({"message": "Invalid email or password"}), 400

@app.route("/logout")
def logout():
    session.pop("user_email", None)
    return redirect(url_for("home"))

# ========== PROFILE ROUTE ==========

@app.route('/profile')
def profile():
    user_email = session.get('user_email')
    if not user_email:
        return redirect(url_for('home'))  # not login page, redirect to home

    user = users.find_one({'email': user_email})
    orders_list = list(orders.find({'email': user_email}))

    return render_template('profile.html', user=user, orders=orders_list)


# ========== ORDER ROUTES ==========

def generate_order_id():
    # Generate a random order ID in the format ORD- followed by 13 digits
    timestamp = str(int(datetime.now().timestamp() * 1000))  # Current time in milliseconds
    return f"ORD-{timestamp}"

@app.route('/api/orders', methods=['POST'])
def create_order():
    try:
        data = request.get_json()
        
        # Generate order data with required fields
        order_data = { # This should probably be generated by MongoDB
            "orderId": generate_order_id(),
            "name": data['name'],
            "email": data['email'],
            "phone": data['phone'],
            "address": data['address'],
            "cart": data['cart'],
            "total": data['total'],
            "date": datetime.now(),
            "__v": 0
        }
        
        # Insert into MongoDB
        result = orders.insert_one(order_data)
        
        # Return the order ID in the response
        return jsonify({
            "success": True,
            "orderId": order_data['orderId'],
            "inserted_id": str(result.inserted_id)
        }), 201
        
    except Exception as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400

@app.route("/api/orders/<order_id>", methods=["GET"])
def get_order(order_id):
    order = orders.find_one({"orderId": order_id})
    if order:
        return jsonify({
            "order": {
                "orderId": order.get("orderId"),
                "name": order.get("name"),
                "email": order.get("email"),
                "phone": order.get("phone"),
                "address": order.get("address"),
                "items": order.get("cart", []),
                "total_amount": order.get("total", 0),
                "order_date": order.get("date").strftime("%Y-%m-%d %H:%M:%S"),
                "payment_mode": order.get("payment_mode")
            }
        })
    return jsonify({"error": "Order not found"}), 404

# ========== CONTACT ROUTE ==========

@app.route("/api/contact", methods=["POST"])
def contact():
    data = request.json
    data["date"] = datetime.now()
    contacts.insert_one(data)
    return jsonify({"message": "Your message has been sent!"}), 201

@app.route('/change-password', methods=['POST'])
def change_password():
    if 'user_id' not in session:
        return jsonify({'success': False, 'message': 'Not authenticated'}), 401
    
    data = request.get_json()
    user = users.find_one({'_id': session['user_id']})
    
    if not user:
        return jsonify({'success': False, 'message': 'User not found'}), 404
    
    if not check_password_hash(user['password'], data['currentPassword']):
        return jsonify({'success': False, 'message': 'Current password is incorrect'}), 401
    
    if len(data['newPassword']) < 8:
        return jsonify({'success': False, 'message': 'Password must be at least 8 characters'}), 400
    
    hashed_password = generate_password_hash(data['newPassword'])
    users.update_one(
        {'_id': session['user_id']},
        {'$set': {'password': hashed_password}}
    )
    
    return jsonify({'success': True, 'message': 'Password updated successfully'})
# ========== STATIC ROUTES ==========

@app.route("/")
def home():
    return send_from_directory(app.static_folder, "index.html")

@app.route("/<path:path>")
def static_files(path):
    return send_from_directory(app.static_folder, path)

# ========== RUN APP ==========

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 3000)))
